"""Cross-repo aggregation (C5).

Scores several repos and renders one portfolio table + badge row, so the
hand-typed, always-stale grade grid in OSS-LAUNCH-CHECKLIST.md becomes a machine
artifact regenerated on a schedule. The table-building and marker-replacement
logic is pure and unit-tested; the CLI wires it to real repo paths.
"""

from __future__ import annotations

from .model import Scorecard

START = "<!-- invigil:portfolio:start -->"
END = "<!-- invigil:portfolio:end -->"


def _top_gaps(sc: Scorecard, n: int = 2) -> str:
    gaps = [f"{r.check.title}" for r in sc.failures()]
    if not gaps:
        return "—"
    shown = "; ".join(gaps[:n])
    return shown + (f" (+{len(gaps) - n} more)" if len(gaps) > n else "")


def build_table(scorecards: list[Scorecard], generated: str) -> str:
    """Render the portfolio as a Markdown table wrapped in replace markers."""
    lines = [
        START,
        f"_Auto-generated by [Invigil](https://github.com/invigil/invigil) on {generated}. Do not edit by hand._",
        "",
        "| Repo | Gate | Grade | Score | Top gaps |",
        "|---|---|---|---|---|",
    ]
    for sc in sorted(scorecards, key=lambda s: (-s.percent, s.repo)):
        lines.append(
            f"| **{sc.repo}** | {sc.gate_level()} | {sc.grade()} | "
            f"{sc.earned}/{sc.possible} ({sc.percent:.0f}%) | {_top_gaps(sc)} |"
        )
    lines += ["", END]
    return "\n".join(lines)


def update_block(document: str, block: str) -> str:
    """Replace the START..END marker block in `document`; append if absent."""
    if START in document and END in document:
        head, _, rest = document.partition(START)
        _, _, tail = rest.partition(END)
        return head + block + tail
    sep = "" if document.endswith("\n") else "\n"
    return f"{document}{sep}\n{block}\n"
